Added notebook demonstrating hyperparameter tuning using tensorboard
GoogleCloudPlatform/vertex-ai-samples pull request #1451
Opened 2023-01-11 00:38 UTC by wjessG

**REQUIRED:** Add a summary of your PR here, typically including why the change is needed and what was changed. Include any design alternatives for discussion purposes.

<br>
--- YOUR PR SUMMARY GOES HERE ---
<br><br><br>

**REQUIRED:** Fill out the below checklists or remove if irrelevant
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this mandatory checklist:
- [ ] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [ ] Follow the style and grammar rules outlined in the above notebook template.
- [ ] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [ ] Passes all the required automated checks. You can locally test for formatting and linting with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
- [ ] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
- [ ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/CODEOWNERS) file under the `Official Notebooks` section, pointing to the author or the author's team.
- [ ] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

<br>

2. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) folder:
- [ ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/CODEOWNERS) file under the `Community Notebooks` section, pointing to the author or the author's team.
- [ ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).

<br>

3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/community-content) folder:
- [ ] Make sure your main `Content Directory Name` is descriptive, informative, and includes some of the key products and attributes of your content, so that it is differentiable from other content
- [ ] The main content directory has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/community-content/CODEOWNERS) file under the `Community Content` section, pointing to the author or the author's team.
- [ ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).

2023-01-11 00:40 UTC, andrewferlitsch commented
@wjessG You need to run the autolinter on the notebook before submitting. See the CONTRIBUTOR GUIDE

2023-01-11 02:48 UTC, andrewferlitsch commented on notebooks/official/tensorboard/tensorboard_vertex_ai_hyperparameter_tuning.ipynb
> +{
<p>TODO to update links</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/1451/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2023-01-11 02:48 UTC, andrewferlitsch commented on notebooks/official/tensorboard/tensorboard_vertex_ai_hyperparameter_tuning.ipynb
> +{
<p>I would move this to the install section. Drop the text explanation</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/1451/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='27'/>

2023-01-11 02:48 UTC, andrewferlitsch commented on notebooks/official/tensorboard/tensorboard_vertex_ai_hyperparameter_tuning.ipynb
> +{
<p>your not installing anything in the code cell</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/1451/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='30'/>

2023-01-11 02:48 UTC, andrewferlitsch commented on notebooks/official/tensorboard/tensorboard_vertex_ai_hyperparameter_tuning.ipynb
> +{
<p>combine 2 text cells</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/1451/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='43'/>

2023-01-11 02:48 UTC, andrewferlitsch commented on notebooks/official/tensorboard/tensorboard_vertex_ai_hyperparameter_tuning.ipynb
> +{
<p>remove TODO</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/1451/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='51'/>

2023-01-13 00:48 UTC, andrewferlitsch approved these changes

2023-01-14 00:48 UTC, jackiejackjack requested changes

2023-01-14 00:48 UTC, jackiejackjack commented on notebooks/official/tensorboard/tensorboard_vertex_ai_hyperparameter_tuning.ipynb
> +        "List the values to try, and log an experiment configuration to TensorBoard. This step is optional: you can provide domain information to enable more precise filtering of hyperparameters in t
Replace with:

Specify the hyperparameter values for the experiment in TensorBoard.

**Optional*: For more fine grained filtering of hyperparameters in the UI, provide domain information and specify which metrics should be displayed.

2023-01-14 01:52 UTC, wjessG commented on notebooks/official/tensorboard/tensorboard_vertex_ai_hyperparameter_tuning.ipynb
> +        "# Vertex AI TensorBoard Hyperparameter Tuning\n",
Hi Jack - That's a good call. I twisted it a little to reflect that TensorBoard's function in this process.

Changed to: "tensorboard_hyperparameter_tuning_with_hparams". This also aligns with open source tensorboard's hyparameter tuning colab. https://www.tensorflow.org/tensorboard/hyperparameter_tuning_with_hparams

2023-01-14 02:09 UTC, wjessG commented on notebooks/official/tensorboard/tensorboard_vertex_ai_hyperparameter_tuning.ipynb
> +        "* Construct a KFP pipeline with your custom training code.\n",
My colab actually doesn't need KFP pipeline. It was added by mistake. I have removed these 3 steps and replaced with accurate description

2023-01-14 02:12 UTC, wjessG commented on notebooks/official/tensorboard/tensorboard_vertex_ai_hyperparameter_tuning.ipynb
> +        "* Vertex AI\n",
It doesn't need cloud storage. I have removed it from Objective part. Sorry for the confusion.

2023-01-14 02:19 UTC, wjessG commented on notebooks/official/tensorboard/tensorboard_vertex_ai_hyperparameter_tuning.ipynb
> +        "Learn about [Vertex AI pricing](https://cloud.google.com/vertex-ai/pricing),\n",
No Cloud storage needed to run this colab.

2023-01-14 02:40 UTC, wjessG commented on notebooks/official/tensorboard/tensorboard_vertex_ai_hyperparameter_tuning.ipynb
> +        "3. [Enable the Vertex AI API](https://console.cloud.google.com/flows/enableapi?apiid=aiplatform.googleapis.com). {TODO: Update the APIs needed for your tutorial. Edit the API names, and upda
No cloud storage API needed.

2023-01-14 02:52 UTC, wjessG commented on notebooks/official/tensorboard/tensorboard_vertex_ai_hyperparameter_tuning.ipynb
> +        "**4. Service account or other**\n",
Since no cloud storage needed. I removed this part.

2023-01-14 02:54 UTC, wjessG commented on notebooks/official/tensorboard/tensorboard_vertex_ai_hyperparameter_tuning.ipynb
> +        "If you run into ImportError: cannot import name 'WKBWriter' from 'shapely.geos', try the following and then restart runtime:"
Thanks for calling this out. This is not needed as it has been addressed in install dependencies.

2023-01-14 04:39 UTC, jackiejackjack reviewed
The part that I reviewed looks good.

2023-01-14 04:39 UTC, jackiejackjack commented on notebooks/official/tensorboard/tensorboard_hyperparameter_tuning_with_hparams.ipynb
> +        "This tutorial shows you how to log hyperparameter experiment results in TensorFlow and visualize the results in TensorBoard's Hparams dashboard.\n",
Hparams --> HParams

2023-01-14 04:39 UTC, jackiejackjack commented on notebooks/official/tensorboard/tensorboard_hyperparameter_tuning_with_hparams.ipynb
> +        "<br> `pip3 install jupyter`\n",
Use the `<pre></pre>` tag for commands instead of code font.

2023-01-14 04:40 UTC, jackiejackjack approved these changes
The part that I reviewed looks good.

2023-01-17 18:50 UTC, telpirion commented
@wjessG it looks like the CI/CD is erroring out on a cell with this line:

```
from google.colab import auth
```

You'll need to have a guardrail around that import statement. 

```
IS_COLAB = "google.colab" in sys.modules
```

2023-01-19 21:55 UTC, telpirion commented
@wjessG It looks like the CI/CD is now having troubles loading Tensorboard. This cell is failing:

```
# Load the TensorBoard notebook extension
%load_ext tensorboard

# Clear any logs from previous runs
!rm -rf ./logs/

# Import TensorFlow and the TensorBoard HParams plugin
import tensorflow as tf
from tensorboard.plugins.hparams import api as hp
```

2023-01-20 02:13 UTC, merged