UUID replaces Timestamp in the notebook template
GoogleCloudPlatform/vertex-ai-samples pull request #745
Opened 2022-07-27 07:13 UTC by krishr2d2

Suggesting changes to the notebooks/notebook_template.ipynb file.

Replaces TIMESTAMP with the UUID to avoid naming conflicts during regression-tests.

2022-07-27 13:33 UTC, soheilazangeneh commented
I like the idea of UUID instead of Timestamp. I am just wondering what kind of naming conflict will happen in regression testing. Can you give me an example?

2022-07-27 13:45 UTC, krishr2d2 commented
> I like the idea of UUID instead of Timestamp. I am just wondering what kind of naming conflict will happen in regression testing. Can you give me an example please?

Since the tests happen parallelly for a bunch of notebooks at a time, there was a scenario where the timestamp(suffix) generated while creating a cloud storage bucket matched in two of the notebooks. Eventually, one of them threw a "bucket not found" exception as the same bucket was cleared by the other notebook by then.

2022-07-27 13:47 UTC, soheilazangeneh commented
> 

Got it! Thanks!

2022-07-27 13:47 UTC, soheilazangeneh approved these changes
LGTM!

2022-07-28 17:45 UTC, ivanmkc requested changes
Logs show a failure:

```
InvalidUrlError: Invalid bucket name in URL "python-docs-samples-testsaip-f5ef7c0f-2095-4725-9e60-dc3bd9556353".
```

2022-07-28 17:50 UTC, soheilazangeneh commented
> 

Where can I find the log containing this error?

2022-08-05 16:54 UTC, ivanmkc commented on notebooks/notebook_template.ipynb
>          "id": "06571eb4063b"
<p>Use </p><p> </p><pre class="ql-syntax" spellcheck="false">def generate_uuid(length: int = 8) -&gt; str: 
  return ''.join(random.choices(string.ascii_lowercase + string.digits, k=length))
</pre>
<br/>

 _Reply via <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/745/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='21'/>

2022-08-08 05:02 UTC, krishr2d2 commented on notebooks/notebook_template.ipynb
>          "id": "06571eb4063b"
Added!!

2022-08-08 15:20 UTC, ivanmkc approved these changes

2022-08-08 15:20 UTC, merged