Rapid prototyping bqml automl
GoogleCloudPlatform/vertex-ai-samples pull request #877
Opened 2022-08-17 10:23 UTC by SamyuktaDR

**REQUIRED:** Add a summary of your PR here, typically including why the change is needed and what was changed. Include any design alternatives for discussion purposes.

<br>
--- YOUR PR SUMMARY GOES HERE ---
<br><br><br>

**REQUIRED:** Fill out the below checklists or remove if irrelevant
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this mandatory checklist:
- [ ] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [ ] Follow the style and grammar rules outlined in the above notebook template.
- [ ] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [ ] Passes all the required automated checks. You can locally test for formatting and linting with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
- [ ] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
- [ ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/CODEOWNERS) file under the `Official Notebooks` section, pointing to the author or the author's team.
- [ ] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

<br>

2. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) folder:
- [ ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/CODEOWNERS) file under the `Community Notebooks` section, pointing to the author or the author's team.
- [ ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).

<br>

3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/community-content) folder:
- [ ] Make sure your main `Content Directory Name` is descriptive, informative, and includes some of the key products and attributes of your content, so that it is differentiable from other content
- [ ] The main content directory has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/community-content/CODEOWNERS) file under the `Community Content` section, pointing to the author or the author's team.
- [ ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).

2022-09-16 17:29 UTC, ivanmkc commented
Missing a PR summary.

2022-09-16 17:33 UTC, ivanmkc commented on notebooks/official/structured_data/rapid_prototyping_bqml_automl.ipynb
>          "id": "k-82uiXlTjvw"
<pre class="ql-syntax" spellcheck="false">Line #2.    BUCKET_URI = f"gs://{BUCKET_NAME}"
</pre><p>Remove this line</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/877/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='24'/>

2022-09-16 17:33 UTC, ivanmkc commented on notebooks/official/structured_data/rapid_prototyping_bqml_automl.ipynb
>          "id": "k-82uiXlTjvw"
<pre class="ql-syntax" spellcheck="false">Line #3.        BUCKET_URI = f"gs://{BUCKET_NAME}"
</pre><p>Move this line outside the if statement.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/877/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='25'/>

2022-09-16 17:33 UTC, ivanmkc commented on notebooks/official/structured_data/rapid_prototyping_bqml_automl.ipynb
>          "id": "k-82uiXlTjvw"
<pre class="ql-syntax" spellcheck="false">Line #1.    if os.getenv("IS_TESTING"):
</pre><p>Are lines 1 to 3 needed? Remove it.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/877/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='40'/>

2022-09-16 17:33 UTC, ivanmkc commented on notebooks/official/structured_data/rapid_prototyping_bqml_automl.ipynb
>          "id": "k-82uiXlTjvw"
<p>Don't use first-person. Should be <code>you validate the endpoint by making a simple prediction to it.</code></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/877/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='56'/>

2022-09-16 17:33 UTC, ivanmkc commented on notebooks/official/structured_data/rapid_prototyping_bqml_automl.ipynb
>          "id": "k-82uiXlTjvw"
<pre class="ql-syntax" spellcheck="false">Line #41.    pipelines = vertex.PipelineJob.list(
</pre><p>Never get the pipeline by pipelines[-1]. It is flaky and non-deterministic. </p><p> </p><p>Get pipeline by a unique ID.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/877/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='66'/>

2022-09-16 17:33 UTC, ivanmkc requested changes
Needs changes.

2022-09-23 06:29 UTC, SamyuktaDR commented
PR Summary : Deleting Bigquery dataset using bigquery client was raising an issue. So instead replace the delete using inline bq command line function. Also added UUID to bq dataset name while creation.

2022-09-24 16:19 UTC, andrewferlitsch approved these changes

2022-09-29 20:17 UTC, merged